---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
source("game_functions.R")
theme_set(theme_minimal())
```

# Little cooperation simulation


The goal of little_cooperation is to simulate the game "little cooperation" to analyze the probability of winning.

Inspired on https://github.com/kjytay/misc/blob/master/blog/2021-01-05%20first_orchard.R

## Game simulation

```{r}
simulate_game(verbose = TRUE) |> knitr::kable()
```


```{r}

# Number of simulations
nsim <- 1000

# Simulate the game and save the results in a tibble
result <- purrr::map_dfr(1:nsim, ~ simulate_game(verbose = FALSE))

cat("Probability of winning:", sum(result$outcome == 1)/nsim * 100, "%\n")

cat("Average of turns:", mean(result$num_turns))

```
## Number of remaining pillars when players win

```{r}

# number of pillars remaining when players win
result |>
  filter(outcome == 1) |>
  ggplot(aes(x = pillars))+
  geom_density(fill = "lightblue")
```

## Number of turns compared to the outcome:

```{r}
result |>
  mutate(outcome = if_else(outcome == 1, "Players win", "Bridge collapses")) |>
  ggplot(aes(x = outcome, y = num_turns, fill=outcome))+
  geom_violin()+
  geom_boxplot(width = 0.1)

```

##

```{r}
result |>
  filter(outcome == 2) |>
  pivot_longer(3:5) |>
  mutate(name = factor(name, levels = c("start", "bridge", "home"))) |> 
  ggplot(aes(x=name, y=value, fill = name))+
  geom_violin(show.legend = F)

```


